import Head from 'next/head'
import Header from '../components/Header'
import P1 from '../components/P1'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mars.png" />
      </Head>

      <Header />
      <P1 />
     
    </div>
  )
}
